apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hexgl-ui
  namespace: hexgl
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hexgl.apps.rke2-harv.kubernerdes.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hexgl
            port:
              number: 8080
